apiVersion: v1
kind: ConfigMap
metadata:
  name: &app-name go-order-cm
  namespace: test-a
  labels:
    app: *app-name
data:
  API_VERSION: "1.0"
  POD_NAME: "go-order.k8"
  PORT: "5010"
  DB_HOST: "rds-proxy-db-arch.proxy-couoacqalfwt.us-east-2.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_SCHEMA: "public"
  DB_DRIVER: "postgres"
  SETPOD_AZ: "false"
  ENV: "dev"  
  OTEL_EXPORTER_OTLP_ENDPOINT: "arch-eks-01-xray-collector.default.svc.cluster.local:4317"
