apiVersion: v1
kind: ConfigMap
metadata:
  name: &app-name go-order-cm
  namespace: test-a
  labels:
    app: *app-name
data:
  VERSION: "1.6"
  ACCOUNT: "az:e5240c8f-ec4f-4bd4-a36e-1981d27dd8e1"
  APP_NAME: "go-order.az1d-aks-architecture"
  PORT: "7004"
  ENV: "dev"

  DB_HOST: "db-az1-arch-01.postgres.database.azure.com"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_MAX_CONNECTION: "10"
  CTX_TIMEOUT: "5"

  LOG_LEVEL: "info" #info, error, warning
  OTEL_EXPORTER_OTLP_ENDPOINT: "arch-aks-az1d-otel-collector.default.svc.cluster.local:4317"

  OTEL_METRICS: "true"
  OTEL_TRACES: "true"
  OTEL_STDOUT_TRACER: "false"

# the features below works only for a local machine, for kubernetes all logs are shipping via a collector
  OTEL_LOGS: "false"
  OTEL_STDOUT_LOG_GROUP: "false"
  LOG_GROUP: "/dock/aks/az1d-aks-architecture/test-a/go-order"

  NAME_SERVICE_00: "go-cart"
  URL_SERVICE_00: "https://go-cart-aws-wk-az.architecturedev.caradhras.io"
  HOST_SERVICE_00: "go-cart"
  CLIENT_HTTP_TIMEOUT_00: "5"

  NAME_SERVICE_01: "go-inventory"
  URL_SERVICE_01: "https://go-inventory-az1d.architecture.caradhras.io"
  HOST_SERVICE_01: "go-inventory"
  CLIENT_HTTP_TIMEOUT_01: "5"

  NAME_SERVICE_02: "go-clearance"
  URL_SERVICE_02: "https://go-clearance-aws-wk-az.architecturedev.caradhras.io"
  HOST_SERVICE_02: "go-clearance"
  CLIENT_HTTP_TIMEOUT_02: "5"
