apiVersion: v1
kind: ConfigMap
metadata:
  name: &app-name go-order-cm
  namespace: test-a
  labels:
    app: *app-name
data:
  API_VERSION: "1.0"
  POD_NAME: "go-order-us-east-1.k8"
  PORT: "5010"
  DB_HOST: "db-arch-03.c944h9fnit72.us-east-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_SCHEMA: "public"
  DB_DRIVER: "postgres"
  SETPOD_AZ: "false"
  ENV: "dev"  
  OTEL_EXPORTER_OTLP_ENDPOINT: "arch-eks-01-xray-collector.default.svc.cluster.local:4317"
  QUEUE_URL_ORDER: "https://sqs.us-east-1.amazonaws.com/908671954593/order.fifo"
  AWS_REGION: "us-east-2"
  POD_QUEUE_TYPE: "sqs"
  ORDER_TABLE_NAME: "order-table"
  BUCKET_NAME: eliezer-992382474575-us-east-1-go-order/
  FILE_PATH: order/